nombre = input("¿cual es tu nombre?")
apellido = input("¿Cual es tu apellido?")
edad = input("¿Cual es tu edad?")
seccion = input("¿En que seccion estas?")
sede = input("¿En que sede estudias?")
print("nombre=" +nombre + apellido)
print("edad" +edad)
print("Seccion"+seccion)
print("Sede"+sede)